# Generated by Django 5.2.16 on 2026-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('college', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('join_date', models.CharField(max_length=30, null=True)),
                ('total_fee', models.CharField(max_length=30, null=True)),
                ('paid_fee', models.CharField(max_length=30, null=True)),
                ('due_fee', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('technology', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
